In [1]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_classification
X, _ = make_classification(n_samples=100, n_features=4, n_clusters_per_class=1,
random_state=42)
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)
print("Cluster Centers:\n", kmeans.cluster_centers_)

Cluster Centers:
 [[ 0.54995517  0.28524553  0.96163041 -1.04670366]
 [ 1.23798946  0.60635612  2.00231725  1.91433481]
 [ 0.2373546   0.11577163  0.38170444  0.42466382]]
